sudo: required

services:
  - docker

language: java
before_install:
- openssl aes-256-cbc -K $encrypted_f774c86c0c1a_key -iv $encrypted_f774c86c0c1a_iv
  -in client-secret.json.enc -out client-secret.json -d
deploy:
  provider: gae
  project: restaurant-solidaire-backend
  keyfile: client-secret.json
  verbosity: debug
  on: master

